package org.domscope

import org.w3c.dom.*

class TagName<E: HTMLElement>(val tagName: String)

object Html {
  val a = TagName<HTMLAnchorElement>("a")
  val area = TagName<HTMLAreaElement>("area")
  val audio = TagName<HTMLAudioElement>("audio")
  val br = TagName<HTMLBRElement>("br")
  val button = TagName<HTMLButtonElement>("button")
  val canvas = TagName<HTMLCanvasElement>("canvas")
  val dl = TagName<HTMLDListElement>("dl")
  val datalist = TagName<HTMLDataListElement>("datalist")
  val data = TagName<HTMLDataElement>("data")
  val details = TagName<HTMLDetailsElement>("details")
  val div = TagName<HTMLDivElement>("div")
  val embed = TagName<HTMLEmbedElement>("embed")
  val fieldset = TagName<HTMLFieldSetElement>("fieldset")
  val font = TagName<HTMLFontElement>("font")
  val form = TagName<HTMLFormElement>("form")
  val hr = TagName<HTMLHRElement>("hr")
  val h1 = TagName<HTMLHeadingElement>("h1")
  val h2 = TagName<HTMLHeadingElement>("h2")
  val h3 = TagName<HTMLHeadingElement>("h3")
  val h4 = TagName<HTMLHeadingElement>("h4")
  val h5 = TagName<HTMLHeadingElement>("h5")
  val h6 = TagName<HTMLHeadingElement>("h6")
  val iframe = TagName<HTMLIFrameElement>("iframe")
  val img = TagName<HTMLImageElement>("img")
  val input = TagName<HTMLInputElement>("input")
  val li = TagName<HTMLLIElement>("li")
  val label = TagName<HTMLLabelElement>("label")
  val legend = TagName<HTMLLegendElement>("legend")
  val link = TagName<HTMLLinkElement>("link")
  val map = TagName<HTMLMapElement>("map")
  val meta = TagName<HTMLMetaElement>("meta")
  val meter = TagName<HTMLMeterElement>("meter")
  val ins = TagName<HTMLModElement>("ins")
  val del = TagName<HTMLModElement>("del")
  val ol = TagName<HTMLOListElement>("ol")
  val obj = TagName<HTMLObjectElement>("object")
  val optgroup = TagName<HTMLOptGroupElement>("optgroup")
  val option = TagName<HTMLOptionElement>("option")
  val output = TagName<HTMLOutputElement>("output")
  val p = TagName<HTMLParagraphElement>("p")
  val param = TagName<HTMLParamElement>("param")
  val progress = TagName<HTMLProgressElement>("progress")
  val blockquote = TagName<HTMLQuoteElement>("blockquote")
  val q = TagName<HTMLQuoteElement>("q")
  val cite = TagName<HTMLQuoteElement>("cite")
  val select = TagName<HTMLSelectElement>("select")
  val source = TagName<HTMLSourceElement>("source")
  val span = TagName<HTMLSpanElement>("span")
  val caption = TagName<HTMLTableCaptionElement>("caption")
  val th = TagName<HTMLTableCellElement>("th")
  val td = TagName<HTMLTableCellElement>("td")
  val col = TagName<HTMLTableColElement>("col")
  val colgroup = TagName<HTMLTableColElement>("colgroup")
  val tr = TagName<HTMLTableRowElement>("tr")
  val table = TagName<HTMLTableElement>("table")
  val tfoot = TagName<HTMLTableSectionElement>("tfoot")
  val thead = TagName<HTMLTableSectionElement>("thead")
  val tbody = TagName<HTMLTableSectionElement>("tbody")
  val textarea = TagName<HTMLTextAreaElement>("textarea")
  val time = TagName<HTMLTimeElement>("time")
  val title = TagName<HTMLTitleElement>("title")
  val track = TagName<HTMLTrackElement>("track")
  val ul = TagName<HTMLUListElement>("ul")
  val video = TagName<HTMLVideoElement>("video")
}